//! Raw declarations for the C ABI. **The only module containing `extern`
//! blocks.**
//!
//! Nothing here is public outside the crate: every item is `pub(crate)`, so the
//! raw structures cannot leak into a caller's types. If a downstream crate could
//! name `supra_ansi_token`, the confinement of `unsafe` to this crate would be
//! nominal rather than real - the caller would end up writing its own unsafe code
//! to use it.
//!
//! Declarations are hand-written rather than generated by bindgen. The ABI is
//! small, stable, and authored in this repository, so a code generator would add
//! a build dependency and a moving part for no benefit. The cost of hand-writing
//! is drift, and that cost is paid down by the compile-time layout assertions
//! below plus the matching `static_assert`s in `abi_check.cpp`.

#![allow(non_camel_case_types)]

use core::ffi::{c_char, c_int, c_void};

/// Layout constants shared with build.rs.
///
/// `abi_sizes.rs` is `include!`d by both this module and build.rs, and build.rs
/// needs the items at its own top level - so they are declared `pub` in the file
/// itself. Inside a private module that reads as unreachable-pub, hence the
/// targeted allow: the visibility is a requirement of the sharing mechanism, not
/// an intent to export.
#[allow(unreachable_pub)]
mod abi {
    include!("../abi_sizes.rs");
}

pub(crate) use abi::*;

// ---------------------------------------------------------------------------
// Limits, mirroring the headers
// ---------------------------------------------------------------------------

pub(crate) const ANSI_MAX_PARAMS: usize = 16;
pub(crate) const ANSI_MAX_SUBPARAMS: usize = 8;
pub(crate) const ANSI_MAX_PAYLOAD: usize = 256;
pub(crate) const ANSI_MAX_TRAILER: usize = 24;
pub(crate) const SANDBOX_MAX_PATHS: usize = 64;
pub(crate) const SANDBOX_MAX_PORTS: usize = 16;
pub(crate) const SANDBOX_ERROR_LEN: usize = 256;

// ---------------------------------------------------------------------------
// libsupra_width
// ---------------------------------------------------------------------------

/// Substituted for malformed input by the decoder.
///
/// Referenced only from tests today. Kept because these constants mirror the
/// header completely, and a partial mirror is where a wrong value gets added
/// later.
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) const WIDTH_REPLACEMENT: u32 = 0xFFFD;
pub(crate) const WIDTH_NONPRINTABLE: c_int = -1;

pub(crate) const AMBIGUOUS_NARROW: c_int = 0;
pub(crate) const AMBIGUOUS_WIDE: c_int = 1;

pub(crate) const VALIDITY_VALID: c_int = 0;
pub(crate) const VALIDITY_INVALID_UTF8: c_int = 1;
pub(crate) const VALIDITY_HAS_NONPRINTABLE: c_int = 2;

unsafe extern "C" {
    pub(crate) fn supra_utf8_decode(
        bytes: *const u8,
        len: usize,
        out_cp: *mut u32,
        consumed: *mut usize,
    ) -> c_int;

    pub(crate) fn supra_utf8_encoded_len(cp: u32) -> usize;

    pub(crate) fn supra_wcwidth(cp: u32, ambiguous: c_int) -> c_int;

    pub(crate) fn supra_grapheme_next(bytes: *const u8, len: usize) -> usize;

    pub(crate) fn supra_grapheme_width(
        bytes: *const u8,
        len: usize,
        ambiguous: c_int,
        out_len: *mut usize,
    ) -> c_int;

    pub(crate) fn supra_wcswidth(bytes: *const u8, len: usize, ambiguous: c_int) -> usize;

    pub(crate) fn supra_width_measure(
        bytes: *const u8,
        len: usize,
        ambiguous: c_int,
        out_clusters: *mut usize,
    ) -> usize;

    pub(crate) fn supra_width_truncate(
        bytes: *const u8,
        len: usize,
        max_cells: usize,
        ambiguous: c_int,
        out_cells: *mut usize,
    ) -> usize;

    pub(crate) fn supra_width_validate(bytes: *const u8, len: usize, out_offset: *mut usize) -> c_int;

    pub(crate) fn supra_width_probe(utf8: *const c_char, ambiguous: c_int) -> c_int;

    pub(crate) fn supra_width_unicode_version() -> *const c_char;
}

// ---------------------------------------------------------------------------
// libsupra_ansi
// ---------------------------------------------------------------------------

pub(crate) const ANSI_TOKEN_TEXT: u8 = 0;
pub(crate) const ANSI_TOKEN_CONTROL: u8 = 1;
pub(crate) const ANSI_TOKEN_CSI: u8 = 2;
pub(crate) const ANSI_TOKEN_ESC: u8 = 3;
pub(crate) const ANSI_TOKEN_OSC: u8 = 4;
pub(crate) const ANSI_TOKEN_DCS: u8 = 5;
pub(crate) const ANSI_TOKEN_APC: u8 = 6;
pub(crate) const ANSI_TOKEN_PARTIAL: u8 = 7;
pub(crate) const ANSI_TOKEN_MALFORMED: u8 = 8;

pub(crate) const ANSI_EOF_MORE: c_int = 0;
pub(crate) const ANSI_EOF_FINAL: c_int = 1;

pub(crate) const ANSI_COLOR_DEFAULT: u8 = 0;
pub(crate) const ANSI_COLOR_INDEXED: u8 = 1;
pub(crate) const ANSI_COLOR_RGB: u8 = 2;

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct supra_ansi_color {
    pub kind: u8,
    pub index: u8,
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct supra_ansi_style {
    pub attrs: u32,
    pub fg: supra_ansi_color,
    pub bg: supra_ansi_color,
    pub underline_color: supra_ansi_color,
    pub underline: u8,
    pub hyperlink_open: u8,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct supra_ansi_token {
    pub kind: u8,
    pub offset: usize,
    pub length: usize,
    pub final_byte: u8,
    pub intermediates: [u8; 2],
    pub intermediate_count: u8,
    pub params: [i32; ANSI_MAX_PARAMS],
    pub param_count: u8,
    pub params_dropped: u8,
    pub subparams: [i32; ANSI_MAX_SUBPARAMS],
    pub subparam_index: [u8; ANSI_MAX_PARAMS],
    pub subparam_count: [u8; ANSI_MAX_PARAMS],
    pub payload: [u8; ANSI_MAX_PAYLOAD],
    pub payload_len: u16,
    pub payload_full: usize,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct supra_ansi_scanner {
    pub state: u8,
    pub pos: usize,
    pub buffer_done: u8,
    pub utf8_expect: u8,
    pub intermediates: [u8; 2],
    pub intermediate_count: u8,
    pub params: [i32; ANSI_MAX_PARAMS],
    pub param_count: u8,
    pub params_dropped: u8,
    pub param_has_digits: u8,
    pub in_subparam: u8,
    pub subparams: [i32; ANSI_MAX_SUBPARAMS],
    pub subparam_total: u8,
    pub subparam_index: [u8; ANSI_MAX_PARAMS],
    pub subparam_count: [u8; ANSI_MAX_PARAMS],
    pub payload: [u8; ANSI_MAX_PAYLOAD],
    pub payload_len: u16,
    pub payload_full: usize,
    pub carried: usize,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct supra_ansi_truncation {
    pub prefix_len: usize,
    pub cells: usize,
    pub trailer: [u8; ANSI_MAX_TRAILER],
    pub trailer_len: u8,
    pub truncated: u8,
    pub style_at_cut: supra_ansi_style,
}

unsafe extern "C" {
    pub(crate) fn supra_ansi_style_default() -> supra_ansi_style;
    pub(crate) fn supra_ansi_style_is_default(style: *const supra_ansi_style) -> c_int;
    pub(crate) fn supra_ansi_style_emit(style: *const supra_ansi_style, out: *mut u8, cap: usize) -> usize;
    pub(crate) fn supra_ansi_style_emit_reset(
        style: *const supra_ansi_style,
        out: *mut u8,
        cap: usize,
    ) -> usize;

    pub(crate) fn supra_ansi_scanner_init(scanner: *mut supra_ansi_scanner);
    pub(crate) fn supra_ansi_scanner_pending(scanner: *const supra_ansi_scanner) -> c_int;
    pub(crate) fn supra_ansi_scan(
        scanner: *mut supra_ansi_scanner,
        bytes: *const u8,
        len: usize,
        eof: c_int,
        out: *mut supra_ansi_token,
    ) -> c_int;

    pub(crate) fn supra_ansi_style_apply(
        style: *mut supra_ansi_style,
        token: *const supra_ansi_token,
    ) -> c_int;
    pub(crate) fn supra_ansi_style_apply_osc(
        style: *mut supra_ansi_style,
        token: *const supra_ansi_token,
    ) -> c_int;

    pub(crate) fn supra_ansi_measure(bytes: *const u8, len: usize, ambiguous: c_int) -> usize;
    pub(crate) fn supra_ansi_strip(bytes: *const u8, len: usize, out: *mut u8, cap: usize) -> usize;

    pub(crate) fn supra_ansi_plan_truncate(
        bytes: *const u8,
        len: usize,
        max_cells: usize,
        ambiguous: c_int,
        out: *mut supra_ansi_truncation,
    );
    pub(crate) fn supra_ansi_plan_truncate_from(
        bytes: *const u8,
        len: usize,
        max_cells: usize,
        ambiguous: c_int,
        initial: *const supra_ansi_style,
        out: *mut supra_ansi_truncation,
    );
}

// ---------------------------------------------------------------------------
// descriptor hygiene (fcntl)
//
// POSIX-fixed commands and flags for the T16 fd primitive, declared by hand
// like every other foreign call in this crate. These are not part of the
// libsupra_* ABI; they are the one libc call with no C++ source beneath it,
// and fd.rs records why. Values are stable across POSIX platforms.
// ---------------------------------------------------------------------------

pub(crate) const F_GETFD: c_int = 1;
pub(crate) const F_SETFD: c_int = 2;
pub(crate) const FD_CLOEXEC: c_int = 1;

// ---------------------------------------------------------------------------
// libsupra_sandbox
// ---------------------------------------------------------------------------

pub(crate) const SANDBOX_TIER_NONE: u8 = 0;
pub(crate) const SANDBOX_TIER_NAMESPACES: u8 = 1;
pub(crate) const SANDBOX_TIER_LANDLOCK: u8 = 2;
pub(crate) const SANDBOX_TIER_SBPL: u8 = 3;
pub(crate) const SANDBOX_TIER_APPCONTAINER: u8 = 4;
pub(crate) const SANDBOX_TIER_UNSET: u8 = 255;

pub(crate) const SANDBOX_READ: u32 = 1 << 0;
pub(crate) const SANDBOX_WRITE: u32 = 1 << 1;
pub(crate) const SANDBOX_EXECUTE: u32 = 1 << 2;
pub(crate) const SANDBOX_MANAGE: u32 = 1 << 3;

pub(crate) const SANDBOX_NET_NONE: u8 = 0;
pub(crate) const SANDBOX_NET_PORTS: u8 = 1;
pub(crate) const SANDBOX_NET_FULL: u8 = 2;

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct supra_sandbox_capabilities {
    pub tier: u8,
    pub landlock_abi: u8,
    pub user_namespaces: u8,
    pub network_isolation: u8,
    pub port_granular_network: u8,
    pub bubblewrap_present: u8,
    pub detail: [c_char; SANDBOX_ERROR_LEN],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct supra_sandbox_path_rule {
    pub path: *const c_char,
    pub access: u32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct supra_sandbox_policy {
    pub paths: [supra_sandbox_path_rule; SANDBOX_MAX_PATHS],
    pub path_count: u8,
    pub network: u8,
    pub allowed_ports: [u16; SANDBOX_MAX_PORTS],
    pub port_count: u8,
    pub isolate_processes: u8,
    pub isolate_ipc: u8,
    pub max_processes: u32,
    pub max_address_space: u64,
    pub max_cpu_seconds: u32,
    pub max_file_size: u64,
    pub required_tier: u8,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct supra_sandbox_process {
    pub pid: i64,
    pub tier: u8,
    pub error: [c_char; SANDBOX_ERROR_LEN],
}

#[repr(C)]
#[derive(Clone, Copy)]
pub(crate) struct supra_sandbox_command {
    pub program: *const c_char,
    pub argv: *const *const c_char,
    pub envp: *const *const c_char,
    pub working_dir: *const c_char,
    pub stdin_fd: c_int,
    pub stdout_fd: c_int,
    pub stderr_fd: c_int,
}

unsafe extern "C" {
    pub(crate) fn supra_sandbox_probe(out: *mut supra_sandbox_capabilities);
    pub(crate) fn supra_sandbox_force_tier_for_testing(tier: u8);

    pub(crate) fn supra_sandbox_policy_init(policy: *mut supra_sandbox_policy);
    pub(crate) fn supra_sandbox_policy_allow(
        policy: *mut supra_sandbox_policy,
        path: *const c_char,
        access: u32,
    ) -> c_int;
    pub(crate) fn supra_sandbox_policy_allow_port(policy: *mut supra_sandbox_policy, port: u16) -> c_int;

    pub(crate) fn supra_sandbox_spawn(
        policy: *const supra_sandbox_policy,
        command: *const supra_sandbox_command,
        out: *mut supra_sandbox_process,
    ) -> c_int;
    pub(crate) fn supra_sandbox_wait(
        process: *const supra_sandbox_process,
        timeout_ms: u32,
        out_status: *mut c_int,
    ) -> c_int;
    pub(crate) fn supra_sandbox_kill(process: *const supra_sandbox_process, grace_ms: u32) -> c_int;

    pub(crate) fn supra_sandbox_self_path(out: *mut c_char, cap: usize) -> usize;
    pub(crate) fn supra_sandbox_self_identity(out_dev: *mut u64, out_ino: *mut u64) -> c_int;
    pub(crate) fn supra_sandbox_file_identity(
        path: *const c_char,
        out_dev: *mut u64,
        out_ino: *mut u64,
    ) -> c_int;
}

// Symbol from abi_check.cpp. Referenced so the linker retains that translation
// unit; its static_asserts are the C++ half of the layout ratchet.
unsafe extern "C" {
    pub(crate) fn supra_ffi_abi_check() -> c_int;
}

// `fcntl` is variadic in C; a single variadic declaration covers both the
// `F_GETFD` (two arguments) and `F_SETFD` (three) shapes, and Rust still
// checks the fixed argument types at every call site. glibc and musl both
// export the plain `fcntl` symbol.
#[cfg(unix)]
unsafe extern "C" {
    pub(crate) fn fcntl(fd: c_int, cmd: c_int, ...) -> c_int;
}

// ---------------------------------------------------------------------------
// pty (T16.5)
//
// The window-size `ioctl` is variadic in C, like `fcntl`; the wrapper passes
// a `winsize` pointer for the two window-size requests it uses. The request
// codes are per-OS constants and live in `pty.rs` next to their use, since
// they describe those two calls rather than a library ABI.
//
// Allocation uses the posix_openpt/grantpt/unlockpt route rather than
// openpty(3): openpty returns both descriptors with FD_CLOEXEC clear, which
// leaves a window where a concurrent fd audit sees the pair as unflagged.
// posix_openpt and open both take O_CLOEXEC, so the flag is set by the
// syscall that creates the descriptor. Declarations for the allocation
// calls follow below.
// ---------------------------------------------------------------------------

#[cfg(unix)]
unsafe extern "C" {
    pub(crate) fn ioctl(fd: c_int, request: core::ffi::c_ulong, ...) -> c_int;
}

// pty allocation, the CLOEXEC-from-birth route (T16.5). `posix_openpt`,
// `grantpt`, and `unlockpt` are POSIX. `ptsname_r` is the GNU thread-safe
// form of `ptsname`; every other Unix ships only the static-buffer
// `ptsname`, which the pty module serialises under a lock. `open` allocates
// the slave descriptor with the O_CLOEXEC the flag-from-birth contract
// needs; the O_ values are per-kernel and live in `pty.rs` next to their
// use.
#[cfg(unix)]
unsafe extern "C" {
    pub(crate) fn posix_openpt(flags: c_int) -> c_int;
    pub(crate) fn grantpt(fd: c_int) -> c_int;
    pub(crate) fn unlockpt(fd: c_int) -> c_int;
    pub(crate) fn open(path: *const c_char, flags: c_int, ...) -> c_int;
}
#[cfg(all(unix, target_os = "linux"))]
unsafe extern "C" {
    pub(crate) fn ptsname_r(fd: c_int, buf: *mut c_char, buflen: usize) -> c_int;
}
#[cfg(all(unix, not(target_os = "linux")))]
unsafe extern "C" {
    pub(crate) fn ptsname(fd: c_int) -> *mut c_char;
}

/// Keep `supra_ffi_abi_check` reachable.
///
/// Without a live reference the linker may drop the object, taking the C++
/// `static_assert`s with it - though only after they have already run at compile
/// time, so this is belt and braces rather than load-bearing.
pub(crate) fn touch_abi_check() -> c_int {
    // SAFETY: takes no arguments, returns a plain int, touches no memory.
    unsafe { supra_ffi_abi_check() }
}

/// Silence the unused-import warning for `c_void`, which exists to document that
/// no opaque handles cross this boundary: every structure is transparent and
/// `#[repr(C)]`, so nothing is passed as an untyped pointer.
const _: Option<*const c_void> = None;

// ---------------------------------------------------------------------------
// Layout ratchet, Rust half
// ---------------------------------------------------------------------------

// The C++ half lives in abi_check.cpp with the same constants. A struct that
// changes on one side without the other fails to compile here or there, so a
// hand-written declaration cannot drift into reading the wrong offsets - the
// failure mode that produces wrong answers rather than a crash.
const _: () = {
    use core::mem::{align_of, size_of};

    assert!(size_of::<supra_ansi_color>() == SIZEOF_ANSI_COLOR);
    assert!(align_of::<supra_ansi_color>() == ALIGNOF_ANSI_COLOR);

    assert!(size_of::<supra_ansi_style>() == SIZEOF_ANSI_STYLE);
    assert!(align_of::<supra_ansi_style>() == ALIGNOF_ANSI_STYLE);

    assert!(size_of::<supra_ansi_token>() == SIZEOF_ANSI_TOKEN);
    assert!(align_of::<supra_ansi_token>() == ALIGNOF_ANSI_TOKEN);

    assert!(size_of::<supra_ansi_scanner>() == SIZEOF_ANSI_SCANNER);
    assert!(align_of::<supra_ansi_scanner>() == ALIGNOF_ANSI_SCANNER);

    assert!(size_of::<supra_ansi_truncation>() == SIZEOF_ANSI_TRUNCATION);
    assert!(align_of::<supra_ansi_truncation>() == ALIGNOF_ANSI_TRUNCATION);

    assert!(size_of::<supra_sandbox_capabilities>() == SIZEOF_SANDBOX_CAPABILITIES);
    assert!(align_of::<supra_sandbox_capabilities>() == ALIGNOF_SANDBOX_CAPABILITIES);

    assert!(size_of::<supra_sandbox_path_rule>() == SIZEOF_SANDBOX_PATH_RULE);
    assert!(align_of::<supra_sandbox_path_rule>() == ALIGNOF_SANDBOX_PATH_RULE);

    assert!(size_of::<supra_sandbox_policy>() == SIZEOF_SANDBOX_POLICY);
    assert!(align_of::<supra_sandbox_policy>() == ALIGNOF_SANDBOX_POLICY);

    assert!(size_of::<supra_sandbox_process>() == SIZEOF_SANDBOX_PROCESS);
    assert!(align_of::<supra_sandbox_process>() == ALIGNOF_SANDBOX_PROCESS);

    assert!(size_of::<supra_sandbox_command>() == SIZEOF_SANDBOX_COMMAND);
    assert!(align_of::<supra_sandbox_command>() == ALIGNOF_SANDBOX_COMMAND);
};
